'use strict';
const crypto = require('crypto');

function tokenHash(token) { return crypto.createHash('sha256').update(String(token || '')).digest('hex'); }
function rankingRows(rows) { return rows.slice(0, 3).map((row) => ({ title: row.title, count: row.request_count })); }
function monthKey(date = new Date(), offset = 0) { const d = new Date(date); d.setDate(1); d.setMonth(d.getMonth() + offset); return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`; }
function safeWebhookUrl(value) { try { const url = new URL(value); return url.protocol === 'https:' && ['discord.com', 'discordapp.com'].includes(url.hostname) && /^\/api\/webhooks\/\d+\//.test(url.pathname) ? url.href : ''; } catch (_) { return ''; } }
function reviewUrl(publicApiUrl, token) { const url = new URL(publicApiUrl || 'https://api.dokkadoki.co.uk'); url.pathname = '/api/manga-results/review'; url.search = new URLSearchParams({ token }).toString(); return url.href; }
function webhookPayload({ month, rankings, url }) { const lines = rankings.length ? rankings.map((item, index) => `${index + 1}. **${item.title}**: ${item.count} vote${item.count === 1 ? '' : 's'}`).join('\n') : 'No eligible requests were submitted.'; return { content: `📚 **Dokkadoki manga rankings awaiting approval**\n**${month}**\n${lines}\n\nReview and approve or reject: ${url}` }; }

async function ensureMangaRankingTables(pool) { await pool.query(`CREATE TABLE IF NOT EXISTS manga_monthly_results (month CHAR(7) PRIMARY KEY, status VARCHAR(16) NOT NULL, rankings_json TEXT NOT NULL, approval_token_hash CHAR(64) NOT NULL, notification_claimed_at TIMESTAMP NULL, notification_sent_at TIMESTAMP NULL, reviewed_at TIMESTAMP NULL, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) CHARACTER SET utf8mb4`); }
async function prepareMonthlyResult({ pool, month, tokenFactory = () => crypto.randomBytes(32).toString('hex') }) { const [existing] = await pool.query('SELECT month, status FROM manga_monthly_results WHERE month = ? LIMIT 1', [month]); if (existing[0]) return { created: false, month, status: existing[0].status, rankings: [], token: '' }; const [rows] = await pool.query('SELECT title, request_count FROM manga_requests WHERE month = ? ORDER BY request_count DESC, updated_at DESC LIMIT 3', [month]); const rankings = rankingRows(rows); const token = tokenFactory(); await pool.query('INSERT INTO manga_monthly_results (month, status, rankings_json, approval_token_hash) VALUES (?, ?, ?, ?)', [month, 'pending', JSON.stringify(rankings), tokenHash(token)]); return { created: true, month, status: 'pending', rankings, token }; }
async function approveMonthlyResult({ pool, token, decision }) { if (!['approved', 'rejected'].includes(decision) || String(token).length < 32) return { updated: false, status: '' }; const [result] = await pool.query("UPDATE manga_monthly_results SET status = ?, reviewed_at = CURRENT_TIMESTAMP WHERE approval_token_hash = ? AND status = 'pending'", [decision, tokenHash(token)]); return { updated: result.affectedRows === 1, status: decision }; }
async function approvedMonthlyResult({ pool, month }) { const [rows] = await pool.query("SELECT rankings_json FROM manga_monthly_results WHERE month = ? AND status = 'approved' LIMIT 1", [month]); try { return rows[0] ? JSON.parse(rows[0].rankings_json) : []; } catch (_) { return []; } }
async function pendingMonthlyResult({ pool, token }) { if (String(token).length < 32) return null; const [rows] = await pool.query("SELECT month, rankings_json FROM manga_monthly_results WHERE approval_token_hash = ? AND status = 'pending' LIMIT 1", [tokenHash(token)]); try { return rows[0] ? { month: rows[0].month, rankings: JSON.parse(rows[0].rankings_json) } : null; } catch (_) { return null; } }
async function claimMonthlyNotification({ pool, month, token }) { const [claim] = await pool.query("UPDATE manga_monthly_results SET approval_token_hash = ?, notification_claimed_at = CURRENT_TIMESTAMP WHERE month = ? AND status = 'pending' AND notification_sent_at IS NULL AND (notification_claimed_at IS NULL OR notification_claimed_at < DATE_SUB(CURRENT_TIMESTAMP, INTERVAL 15 MINUTE))", [tokenHash(token), month]); if (claim.affectedRows !== 1) return null; const [rows] = await pool.query('SELECT rankings_json FROM manga_monthly_results WHERE month = ? LIMIT 1', [month]); try { return JSON.parse(rows[0].rankings_json); } catch (_) { return null; } }
async function runMangaRankingReview({ pool, config = {}, now = new Date(), fetchImpl = fetch, tokenFactory = () => crypto.randomBytes(32).toString('hex') }) { const month = monthKey(now, -1); await prepareMonthlyResult({ pool, month, tokenFactory }); const webhookUrl = safeWebhookUrl(config.webhookUrl); if (!webhookUrl) return { month, sent: false, reason: 'webhook-not-configured' }; const token = tokenFactory(); const rankings = await claimMonthlyNotification({ pool, month, token }); if (!rankings) return { month, sent: false, reason: 'already-notified' }; try { const response = await fetchImpl(webhookUrl, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(webhookPayload({ month, rankings, url: reviewUrl(config.publicApiUrl, token) })), signal: AbortSignal.timeout(10_000) }); if (!response.ok) throw new Error(`Discord webhook failed (${response.status})`); await pool.query('UPDATE manga_monthly_results SET notification_sent_at = CURRENT_TIMESTAMP WHERE month = ?', [month]); return { month, sent: true }; } catch (error) { await pool.query('UPDATE manga_monthly_results SET notification_claimed_at = NULL WHERE month = ?', [month]); throw error; } }
function rankingIntervalMs(value) { const n = Number(value); return Number.isInteger(n) && n >= 60_000 && n <= 3_600_000 ? n : 300_000; }
async function startMangaRankingReview({ pool, config, intervalMs, log = console, setIntervalImpl = setInterval }) { const run = () => runMangaRankingReview({ pool, config }).catch((error) => { log.error?.(`Manga ranking review failed: ${error.message}`); return { sent: false, error: true }; }); await run(); setIntervalImpl(() => { void run(); }, rankingIntervalMs(intervalMs)); }
module.exports = { approveMonthlyResult, approvedMonthlyResult, ensureMangaRankingTables, monthKey, pendingMonthlyResult, prepareMonthlyResult, rankingIntervalMs, rankingRows, reviewUrl, runMangaRankingReview, safeWebhookUrl, startMangaRankingReview, tokenHash, webhookPayload };
